# client (Pod) 的身份，K8s 會把這個 SA 的 Token/CA 掛載進 Pod，然後用它連 API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dm-incluster
  namespace: default
---
# 定義 Role：描述 dm-role 可以對哪些資源做什麼操作
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dm-role
  namespace: default
rules:
  - apiGroups: 
      - "apps" # apps API 群組底下的資源
      - "" # core API 群組（空字串），就是 Pod/Service 這些
    resources:
      - deployments
      - services
    verbs:
      - get 
      - create
      - delete
---
# 定義 RoleBinding：把 dm-role 的規則授權給 dm-incluster 這個 SA 使用
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dm-incluster-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dm-role
subjects:
  - kind: ServiceAccount
    name: dm-incluster
    namespace: default