# client (Pod) 的身份，K8s 會把這個 SA 的 Token/CA 掛載進 Pod，然後用它連 API
# 一個帳號
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dm-incluster
  namespace: default
---
# 定義 Role：描述 dm-role 可以對哪些資源做什麼操作
# 權限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dm-role
  namespace: default
rules:
  # apps 群組：deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "delete", "list"]

  # core 群組：services、pods
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "delete", "list"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
# 定義 RoleBinding：把 dm-role 的規則授權給 dm-incluster 這個 SA 使用
# 把帳號跟權限綁在一起
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dm-incluster-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dm-role
subjects:
  - kind: ServiceAccount
    name: dm-incluster
    namespace: default